[package]
name = "nowfile"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
rust-s3 = "0.19.0"
object-pool = "0.4.4"
rand = "0.7.3"
chrono = "0.4.11"
actix-multipart = "0.2.0"
futures = "0.3.4"
serde = "1.0.105"
serde_json = "1.0.48"
base64 = "0.12.0"
slog = "2.5.2"
slog-async = "2.3.0"
slog-term = "2.4.2"
mime_guess = "2.0.3"
